/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/anonymizer/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_anonymizer_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anonymizer/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_anonymizer_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anonymizer/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_anonymizer__job_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_anonymizer__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anonymizer/{job_id}/findings/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Manual Finding */
        post: operations["add_manual_finding_api_anonymizer__job_id__findings_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anonymizer/{job_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["apply_api_anonymizer__job_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anonymizer/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_anonymizer__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generator/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze For Generation */
        post: operations["analyze_for_generation_api_generator_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generator/{job_id}/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Template */
        post: operations["repair_template_api_generator__job_id__repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generator/{job_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Document */
        post: operations["generate_document_api_generator__job_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generator/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Generated */
        get: operations["download_generated_api_generator__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnonymizerJobResponse */
        AnonymizerJobResponse: {
            /** Job Id */
            job_id: string;
            /** Filename */
            filename: string;
            /**
             * Document Format
             * @enum {string}
             */
            document_format: "docx" | "pdf" | "pptx";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "extracting" | "detecting" | "review_ready" | "applying" | "ready" | "failed";
            /** Progress */
            progress: number;
            /** Error */
            error: string | null;
            /** Expires In Minutes */
            expires_in_minutes: number;
            /** Limitations */
            limitations: string[];
            /** Findings */
            findings: components["schemas"]["FindingResponse"][];
            /** Groups */
            groups: components["schemas"]["FindingGroupResponse"][];
            /** Blocks */
            blocks: components["schemas"]["TextBlockResponse"][];
            /** Coverage Issues */
            coverage_issues: components["schemas"]["CoverageIssueResponse"][];
            /** Summary */
            summary: {
                [key: string]: number;
            };
            /** Applied Count */
            applied_count?: number | null;
            /** Remaining Count */
            remaining_count?: number | null;
            /** Download Url */
            download_url?: string | null;
            /** Output Filename */
            output_filename?: string | null;
        };
        /** ApplyRequest */
        ApplyRequest: {
            /** Decisions */
            decisions: components["schemas"]["GroupDecision"][];
            /**
             * Review Confirmed
             * @default false
             */
            review_confirmed: boolean;
            /**
             * Remove Unsupported Content
             * @default false
             */
            remove_unsupported_content: boolean;
        };
        /** Body_analyze_api_anonymizer_analyze_post */
        Body_analyze_api_anonymizer_analyze_post: {
            /** File */
            file: string;
            /**
             * Options
             * @default {}
             */
            options: string;
        };
        /** Body_analyze_for_generation_api_generator_analyze_post */
        Body_analyze_for_generation_api_generator_analyze_post: {
            /** File */
            file: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Formats */
            formats: components["schemas"]["FormatCapability"][];
            /** Features */
            features: {
                [key: string]: boolean;
            };
            /** Categories */
            categories: components["schemas"]["CategoryCapability"][];
            /**
             * Default Profile
             * @constant
             */
            default_profile: "maximum";
            model: components["schemas"]["ModelCapability"];
            limits: components["schemas"]["LimitsCapability"];
        };
        /** CategoryCapability */
        CategoryCapability: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Enabled By Default */
            enabled_by_default: boolean;
        };
        /** CoverageIssueResponse */
        CoverageIssueResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Blocking */
            blocking: boolean;
            /** Removable */
            removable: boolean;
        };
        /** FindingGroupResponse */
        FindingGroupResponse: {
            /** Id */
            id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Replacement */
            replacement: string;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Band
             * @enum {string}
             */
            confidence_band: "validated" | "probable" | "review";
            /** Finding Ids */
            finding_ids: string[];
            /** Occurrence Count */
            occurrence_count: number;
            /** Sources */
            sources: string[];
            /** Reason */
            reason: string;
            /** Selected By Default */
            selected_by_default: boolean;
        };
        /** FindingResponse */
        FindingResponse: {
            /** Id */
            id: string;
            /** Group Id */
            group_id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Replacement */
            replacement: string;
            location: components["schemas"]["LocationResponse"];
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Context */
            context: string;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Band
             * @enum {string}
             */
            confidence_band: "validated" | "probable" | "review";
            /** Sources */
            sources: string[];
            /** Reason */
            reason: string;
            /** Selected By Default */
            selected_by_default: boolean;
            /** Is Manual */
            is_manual: boolean;
        };
        /** FormatCapability */
        FormatCapability: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Enabled */
            enabled: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** GenerateDocumentRequest */
        GenerateDocumentRequest: {
            /** Context */
            context?: {
                [key: string]: string;
            };
        };
        /** GroupDecision */
        GroupDecision: {
            /** Group Id */
            group_id: string;
            /**
             * Action
             * @default replace
             * @enum {string}
             */
            action: "replace" | "keep";
            /** Replacement */
            replacement?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LimitsCapability */
        LimitsCapability: {
            /** Compressed Mb */
            compressed_mb: number;
            /** Expanded Mb */
            expanded_mb: number;
            /** Retention Minutes */
            retention_minutes: number;
        };
        /** LocationResponse */
        LocationResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "docx" | "pdf" | "pptx";
            /** Part */
            part: string;
            /** Block Index */
            block_index: number;
            /** Label */
            label: string;
        };
        /** ManualFindingRequest */
        ManualFindingRequest: {
            /** Block Id */
            block_id: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Entity Type */
            entity_type: string;
            /**
             * All Occurrences
             * @default true
             */
            all_occurrences: boolean;
        };
        /** ModelCapability */
        ModelCapability: {
            /** Ready */
            ready: boolean;
            /** Provider */
            provider: string;
            /** Version */
            version: string;
            /** Detail */
            detail: string;
            /** Local Only */
            local_only: boolean;
        };
        /** TextBlockResponse */
        TextBlockResponse: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            location: components["schemas"]["LocationResponse"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_anonymizer_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    analyze_api_anonymizer_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_anonymizer_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymizerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_anonymizer__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymizerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_anonymizer__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_manual_finding_api_anonymizer__job_id__findings_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualFindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymizerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_api_anonymizer__job_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymizerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_anonymizer__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    analyze_for_generation_api_generator_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_for_generation_api_generator_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_template_api_generator__job_id__repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_document_api_generator__job_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_generated_api_generator__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
